const express = require("express");
const router = express.Router();

//Get terms lebanon
router.get("/lebanon", async (req, res) => {
  let result = [];
  result.push({ terms:
`PLEASE READ THESE TERMS OF USE CAREFULLY. DOWNLOADING, INSTALLING, ACCESSING OR USING THIS B.HIVE MOBILE APPLICATION (THE “APPLICATION”) CONSTITUTES ACCEPTANCE OF THESE TERMS OF USE (“TERMS”), AS SUCH MAY BE REVISED BY B.HIVE FROM TIME TO TIME, AND IS A BINDING AGREEMENT BETWEEN THE USER (“USER”), AND The B.HIVE CAFÉ CORPORATION , GOVERNING THE USE OF THE APPLICATION. IF USER DOES NOT AGREE TO THESE TERMS, USER SHOULD UNINSTALL THIS APPLICATION IMMEDIATELY. THESE TERMS CONTAIN DISCLAIMERS AND OTHER PROVISIONS THAT LIMIT OUR LIABILITY TO USER.

These terms include an Arbitration provision that governs any disputes between you and us. Except where prohibited by law, this provision will:

Eliminate your right to a trial by jury; and
Substantially affect your rights, including preventing you from bringing, joining or participating in class or consolidated proceedings.
You agree that we may provide notices, disclosures and amendments to these Terms by electronic means, including by changing these Terms within the Application or by posting revisions on the B.Hive Website.


Eligibility
The Application is not targeted towards, nor intended for use by, anyone under the age of 13. A USER MUST BE AT LEAST AGE 13 TO ACCESS AND USE THE APPLICATION. If the User is between the ages of 13 and the age of majority in his or her province/territory of residence, he or she may only use the Application under the supervision of a parent or legal guardian who agrees to be bound by these Terms.
In order to use certain functions of our Application, you will need to register for an account. You agree to (a) create only one account; (b) provide accurate, truthful , current and complete information when creating your account; (c) maintain and promptly update your account information; (d) maintain the security of your account by not sharing your password with others and restricting access to your account and your computer; (e) promptly notify B.HIVE if you discover or otherwise suspect any security breaches relating to the Application; and (f) take responsibility for all activities that occur under your account and accept all risks of unauthorized access.

Privacy
Please read the Privacy Policy carefully to understand how B.HIVE collects, uses and discloses personally identifiable information from its users. By downloading, installing, accessing or using the Application, you consent to all actions that we take with respect to your data consistent with our Privacy Policy. 

Third Party Terms and Conditions; B.HIVE Policies
These Terms supplement and incorporate (i) the terms and conditions of any site from which User downloads the Application (including Google Play, the Amazon Appstore, and the Android Market) (“Third Party Terms”) and (ii) other B.HIVE policies. If any of the provisions of the Third Party Terms or any applicable B.HIVE policies conflict with these Terms, these Terms will control, solely to the extent such terms apply to the Application.


Mobile Payment
Users who download the Application to a Device may also elect to participate in certain functionality of the Application which will allow the User to use a Device to purchase B.HIVE products (a) using a digital B.HIVE Card and/or (b) by linking a credit card, debit card or mobile wallet to your account, and using it to pay directly for the products through the Application (“Mobile Payment”). Mobile Payment is accepted at all company operated B.HIVE retail locations and some B.HIVE licensed stores. B.HIVE reserves the right at any time to discontinue Mobile Payment or change the location of stores accepting Mobile Payment.

Mobile Order and Pay (MOP)
Users who download the Application to a Device may also elect to participate in certain functionality of the Application which will allow the User in certain B.HIVE retail locations in certain markets to use the Application to order and pay for certain B.HIVE products prior to arrival at the store (“MOP”). B.HIVE reserves the right to limit the ordering options available through MOP, including a limit of twelve (12) or fewer of each potential beverage modifier (e.g., number of espresso shots, number of pumps of flavored syrup, etc.) per each MOP item ordered. B.HIVE reserves the right at any time to discontinue MOP, to change the location of stores or markets offering MOP, and/or to change the ordering options and limitations for items through MOP.

Email Communications, Push Notifications, and In-App Messages
If a User signs up for a B.HIVE account using the Application, the User may choose to opt in to receive promotional email communications from B.HIVE (“Email Communications”). The User may, at any time, opt out of receiving Email Communications from B.HIVE by adjusting the User’s profile settings.
Similarly, upon download of this Application, the User is provided the option to opt in to receive push notifications from B.HIVE on his or her Device. This may include promotional communications, offers, and system messages pushed to the Device or within the Application mailbox (“Push Notifications”). The User may, at any time following download of this Application, opt out of receiving Push Notifications by type by adjusting the “B.HIVE Notifications” switch within the Application settings to “off”, or within the Device’s settings application under “Notifications” to completely opt out of Push Notifications. Opting out of Push Notifications will not affect User settings with respect to Email Communications.
Finally, by using this Application, in-app messages will automatically be displayed to the User via the Application’s display tiles and/or sent to the User via the Application’s inbox, including promotional communications and offers. If the User does not wish to see or receive such messages, the User must cease use of the Application.

Copyright, Trademarks, and User License
Unless otherwise indicated, the Application and all content and other materials therein, including, without limitation, the B.HIVE logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Application Materials”) are the property of B.HIVE or its licensors or users and are protected by Canadian and international copyright laws. B.HIVE Coffee Company, B.HIVE, the B.HIVE logo, and other B.HIVE trademarks, service marks, graphics, and logos used in connection with the Application are trade names, trademarks or registered trademarks of B.HIVE Corporation (collectively “B.HIVE Marks”). Other trademarks, service marks, graphics and logos used in connection with the Application are the trademarks or registered trademarks of their respective owners (collectively “Third Party Marks”). The B.HIVE Marks and Third-Party Marks may not be copied, imitated, or used, in whole or in part, without the prior written permission of B.HIVE or the applicable trademark holder. The Application and the Content are protected by copyright, trademark, patent, trade secret, international treaties, provincial and federal laws, and other proprietary rights and also may have security components that protect digital information only as authorized by B.HIVE or the owner of the Content. All rights not expressly granted are reserved. 

Subject to these Terms, B.HIVE grants the User a personal, non-exclusive, non-transferable, limited, and revocable license to use the Application for personal use only in accordance with these Terms (“User License”). Any use of the Application in any other manner, including, without limitation, resale, transfer, modification or distribution of the Application or text, pictures, music, barcodes, video, data, hyperlinks, displays, and other content associated with the Application (“Content”) is prohibited. Unless explicitly stated herein, nothing in these Terms shall be construed as conferring in any manner, whether by implication, estoppel or otherwise, any title or ownership of, or exclusive use-rights to, any intellectual property or other right and any goodwill associated therewith These Terms and User License also govern any updates to, or supplements or replacements for, the Application, unless separate terms accompany such updates, supplements, or replacements, in which case the separate terms will apply.

Acceptable Use
User’s use of the Application, any Content, and any information provided by the User including user names and passwords, addresses, e-mail addresses, phone number, financial information (such as credit card numbers), information related to a B.HIVE Card, employer name, or GPS location (“User Information”) transmitted in connection with the Application is limited to the contemplated functionality of the Application. In no event may the Application be used in a manner that (a) harasses, abuses, stalks, threatens, defames, or otherwise infringes or violates the rights of any other party (including but not limited to rights of publicity or other proprietary rights); (b) is unlawful, fraudulent, or deceptive; (c) provides sensitive personal information unless specifically requested by B.HIVE, (d) includes spam or any unsolicited advertising; (e) uses technology or other means to access B.HIVE or Content that is not authorized by B.HIVE; (f) uses or launches any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” to access B.HIVE or Content; (g) attempts to introduce viruses or any other computer code, files, or programs that interrupt, destroy, or limit the functionality of any computer software, hardware, or telecommunications equipment; (h) attempts to gain unauthorized access to B.HIVE’ computer network or user accounts; (i) encourages conduct that would constitute a criminal offense or that gives rise to civil liability; (j) violates these Terms; (k) attempts to damage, disable, overburden, or impair B.HIVE’ servers or networks; (l) impersonates any person or entity or otherwise misrepresents your identity or affiliation with another person or entity; or (m) fails to comply with applicable third party terms (collectively “Acceptable Use”). B.HIVE reserves the right, in its sole discretion, to terminate any User License, terminate any User’s participation in Mobile Payment or MOP, remove Content, or assert legal action with respect to Content or use of the Application, including Mobile Payment or MOP, that B.HIVE reasonably believes is or might be in violation of these Terms, Third Party Terms, or B.HIVE policies including the B.HIVE Card Terms and Conditions. B.HIVE’ failure or delay in taking such actions does not constitute a waiver of its rights to enforce these Terms. B.HIVE requests that Users not use the Application, including that they not place orders through MOP, while driving.

Indemnification
The User agrees to defend, indemnify, and hold harmless B.HIVE, its parent, subsidiary and other affiliated companies, independent contractors, service providers and consultants, and their respective employees, contractors, agents, officers, and directors (“B.HIVE Indemnitees”) from any and all claims, suits, damages, costs, lawsuits, fines, penalties, liabilities, and expenses (including attorneys’ fees) (“Claims”) that arise from or relate to the User’s use or misuse of the Application (including Mobile Payment or MOP), violation of these Terms, or violation of any rights of a third party. Notwithstanding the foregoing, this indemnification provision shall not apply to any Claims caused by a B.HIVE Indemnitee’s sole negligence. B.HIVE reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by the User, in which event the User will cooperate in asserting any available defenses.

Warranties; Disclaimers
B.HIVE IS PROVIDING THE APPLICATION TO THE USER “AS IS” AND THE USER IS USING THE APPLICATION AT HIS OR HER OWN RISK. TO THE FULLEST EXTENT ALLOWABLE UNDER APPLICABLE LAW, B.HIVE DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES THAT THE APPLICATION IS MERCHANTABLE, RELIABLE, AVAILABLE, ACCURATE, FIT FOR A PARTICULAR PURPOSE OR NEED, NON-INFRINGING, FREE OF DEFECTS OR VIRUSES, ABLE TO OPERATE ON AN UNINTERRUPTED BASIS, THAT THE USE OF THE APPLICATION BY THE USER IS IN COMPLIANCE WITH LAWS APPLICABLE TO THE USER, THAT USER INFORMATION OR ORDERS TRANSMITTED IN CONNECTION WITH THE APPLICATION (INCLUDING AS PART OF MOBILE PAYMENT OR MOP) WILL BE SUCCESSFULLY, ACCURATELY, OR SECURELY TRANSMITTED OR RECEIVED, THAT ORDERS WILL BE AS PLACED OR READY AT THE SUGGESTED TIME, OR THAT ANY PARTICULAR ITEM ORDERED WILL BE AVAILABLE. THE MATERIALS AND INFORMATION IN THE APPLICATION MAY INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS.
ANY PRODUCTS AND/OR SERVICES DESCRIBED ON THE APPLICATION ARE OFFERED IN JURISDICTIONS WHERE THEY MAY BE LEGALLY OFFERED FOR SALE. THE INFORMATION AVAILABLE ON OR THROUGH THE APPLICATION IS NOT AN OFFER OR SOLICITATION BY ANYONE TO ANYONE IN ANY JURISDICTION IN WHICH AN OFFER OR SOLICITATION CANNOT LEGALLY BE MADE, OR TO ANY PERSON TO WHOM IT IS UNLAWFUL TO MAKE A SOLICITATION.

No Liability
SUBJECT TO APPLICABLE LAW, IN NO EVENT SHALL B.HIVE OR ITS OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS OR AGENTS (A) BE LIABLE TO THE USER WITH RESPECT TO USE OF THE APPLICATION, INCLUDING WITHOUT LIMITATION PARTICIPATION IN MOBILE PAYMENT OR MOP, THE CONTENT OR THE MATERIALS CONTAINED IN OR ACCESSED THROUGH THE APPLICATION, OR ANY DAMAGES THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO B.HIVE' RECORDS, PROGRAMS OR SERVICES; AND (B) BE LIABLE TO THE USER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, LOST PROFITS, LOSS, THEFT OR CORRUPTION OF USER INFORMATION, THE INABILITY TO USE THE APPLICATION OR ANY OF ITS FEATURES OR DEVICE FAILURE OR MALFUNCTION. THE USER’S SOLE REMEDY IS TO CEASE USE OF THE APPLICATION OR TO CEASE PARTICIPATION IN MOBILE PAYMENT OR MOP.
YOUR JURISDICTION MAY NOT ALLOW THE LIMITATION OF LIABILITY IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THESE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.

Third Party Content, Applications, Products and Services (including Advertising and Promotions)
B.HIVE may provide third party content in the Application (including embedded content) or links to third party content, applications, products and services, including advertisements and promotions (collectively, “Third Party Content”) as a service to those interested in this information. We do not control, endorse or adopt any Third-Party Content, including that the inclusion of any link does not imply affiliation, endorsement or adoption by B.HIVE of any application or any information contained therein, and can make no guarantee as to its accuracy or completeness. You acknowledge and agree that B.HIVE is not responsible or liable in any manner for any Third-Party Content and undertakes no responsibility to update or review such Third-Party Content. You agree to use such Third-Party Content contained therein at your own risk. When you use other applications via Third-Party Content, or participate in promotions or business dealings with third parties, you should understand that our terms and policies no longer govern, and that the terms and policies of those third-party applications will now apply. You should review the applicable terms and policies, including privacy and data gathering practices, of any application to which you navigate from our Application. You must comply with any applicable third-party terms when using the Application.

Modifications to the Application
B.HIVE reserves the right to modify or discontinue, temporarily or permanently, the Application or any features or portions thereof without prior notice. You agree that B.HIVE will not be liable for any modification, suspension or discontinuance of the Application or any part thereof.

Arbitration
Please read this section carefully. It affects rights that you may otherwise have. It provides for resolution of most disputes through arbitration instead of court trials and class actions. Arbitration is more informal than a lawsuit in court, uses a neutral arbitrator instead of a judge or jury, and discovery is more limited. Arbitration is final and binding and subject to only very limited review by a court. This arbitration clause shall survive termination of these Terms.

Binding Arbitration.　This provision is intended to be interpreted broadly to encompass all disputes or claims arising out of or relating to these Terms, your use of the Application, and your relationship with us. Any dispute or claim arising out of or relating to these Terms or use of the Application and your relationship with B.HIVE or any subsidiary, parent or affiliate company or companies (whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory) will be resolved by binding arbitration, except that either of us may take claims to small claims court if they qualify for hearing by such a court.

Arbitration Procedures.　For all disputes, whether pursued in court or arbitration, you must first send a written description of your claim to our Customer Service department to allow us an opportunity to resolve the dispute. You and we each agree to negotiate your claim in good faith. You may request arbitration if your claim or dispute cannot be resolved within 60 days.
The arbitration of any dispute or claim shall be conducted and finally resolved in accordance with the rules of the Canadian Arbitration Association ("CAA"), including the CAA's Arbitration Rules (as applicable), as modified by these Terms. The CAA Rules and information about arbitration and fees are available online at https://canadianarbitrationassociation.ca. Any arbitration will be held in a reasonably convenient location in the province in which you reside or at another mutually agreed location. The arbitration will be conducted in the English language unless otherwise mutually agreed by us in writing or otherwise required by law. An arbitrator may award on an individual basis any relief that would be available in a court, including injunctive or declaratory relief to the extent required to satisfy your individual claim, and must follow and enforce these Terms as a court would. Any arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award. Judgment on any arbitration award may be entered in any court having proper jurisdiction. There will be no appeal from the decision of the arbitrator on questions of fact, law, or mixed fact and law.

Costs of Arbitration.　 Each party will bear the fees and expense of its own attorneys, experts, witnesses and preparation and presentation of evidence at the arbitration. 

Class Action Waiver and Jury Waiver.　Unless otherwise prohibited by law, you and we each agree that any proceeding, whether in arbitration or in court, will be conducted only on an individual basis and not in a class, consolidated or representative action. If a court or arbitrator determines in an action between you and us that this class action waiver is unenforceable, the arbitration agreement will be void as to you. If for any reason a claim proceeds in court rather than through arbitration, you and we each waive any right to a jury trial.

Governing Law and Jurisdiction
These Terms and use of the Application are governed by the laws of Canada and the law of the Province of Quebec applicable therein, without resort to conflict of law provisions. The United Nations Convention on Contracts for the International Sale of Goods shall have no applicability. If the arbitration agreement is ever deemed unenforceable or void or a dispute between the parties is not subject to arbitration, the User irrevocably consents to the exclusive jurisdiction of the courts in Montreal, Quebec, Canada for purposes of any legal action arising out of or related to the use of the Application or these Terms.

Termination
Notwithstanding any of these Terms, B.HIVE reserves the right, without notice and in its sole discretion, to terminate your license to use the Application and to block or prevent your future access to and use of the Application. B.HIVE’ failure or delay in taking such actions does not constitute a waiver of its rights to enforce these Terms.

Changes
B.HIVE reserves the right to change or modify these Terms or any other B.HIVE policies related to use of the Application at any time and at its sole discretion by changing these Terms within the Application or by posting revisions on the B.HIVE Website. Continued use of the Application following such changes or modifications to the Terms or other B.HIVE policies will constitute acceptance of such changes or modifications. If you do not agree to such changes or modifications, you should uninstall the Application immediately.

Severability
If any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.

Language
By using the English version of the Application, the parties acknowledge and agree that they have required that this Agreement be prepared in the English language. En utilisant la version anglaise de l’application, les parties reconnaissent avoir exigé que la présente convention soit rédigée en anglais.

Contact
Any questions, complaints, or claims regarding the Application should be directed to:

THE B.HIVE CAFÉ CORPORATION
contact@thebhive.io
2313 Saint Catherine, 106/107
Montreal, QC H3H 1N2
` 
});
  result.push({ privacy: `Please read the following provisions carefully to understand how B.HIVE collects, uses and discloses personally identifiable information from its users, including with respect to the B.HIVE mobile application (“Application”). By downloading, installing, accessing or using the Application, you consent to all actions that we take with respect to your data consistent with our Privacy Policy and the following provisions.

User Information
Some functionality of the Application, including using a device operating on an Android platform (“Device”) to purchase B.HIVE products in the same manner as is possible with a B.HIVE stored value card (“B.HIVE Card”) (“Mobile Payment”), using the Application to order and pay for certain B.HIVE products using a B.HIVE stored value card prior to arrival at the store (“MOP”), location-based services and functionality, iBeacons or other location-based technology to enhance the user experience, and access of User’s address book may require the transmission of information provided by the User including user names and passwords, addresses, e-mail addresses, phone number, financial information (such as credit card numbers), information related to a B.HIVE Card, employer name, or GPS location (“User Information”). In order to use certain Application functionality, such as MOP and location-based services and technology, User must either (a) enable “location services” in the Application; and/or (b) set the permissions in his or her mobile device to allow communication of this information. If the User uses such Application functionality, the User consents to the transmission of User Information to B.HIVE and/or its agents, and authorizes B.HIVE and/or its agents to record, process, and store such User Information as necessary for the Application functionality and for purposes described in the B.HIVE Privacy Policy. Please see the Privacy Policy for more information about how we may use and store such User Information, and how to opt out of sharing User Information, including GPS location.
  
  
The User is solely responsible for maintenance of the confidentiality and security of any User Information which the User transmitted from or stored on a Device for purposes of the Application, including Mobile Payment and MOP, for all transactions and other activities undertaken with any B.HIVE Card registered in the User’s name, whether authorized or unauthorized. The User agrees to immediately notify B.HIVE of any unauthorized transactions associated with the Application including Mobile Payment and MOP, or any other breach of security. B.HIVE shall not be responsible for any losses arising out of the loss or theft of User Information which the User transmitted from or stored on a Device or from unauthorized or fraudulent transactions associated with the Application.
  
Email Communications and Push Notifications
If a User signs up for a B.HIVE account using the Application, the User will have the opportunity to opt-in to receive promotional email communications from B.HIVE (“Email Communications”). Thereafter, the User may opt out of receiving Email Communications solely by adjusting the User’s profile settings.
  
Similarly, upon download of this Application, the User is, provided the option to opt into receive push notifications from B.HIVE on their Device and within the Application. This may include promotional communications, Pick of the Week offers, and system messages pushed to the Device or within the Application mailbox (“Push Notifications”). The User may, at any time following download of this Application, opt out of receiving Push Notifications by type by adjusting the “B.HIVE Notifications” switch within the Application settings to “off", or within the Device’s settings application under "Notifications" to completely opt out of Push Notifications. Opting out of Push Notifications will not affect User settings with respect to Email Communications.
  ` });
  res.status(201).send(result);
});

//Get terms canada
router.get("/canada", async (req, res) => {
  let result = [];
  result.push({ terms:
`PLEASE READ THESE TERMS OF USE CAREFULLY. DOWNLOADING, INSTALLING, ACCESSING OR USING THIS B.HIVE MOBILE APPLICATION (THE “APPLICATION”) CONSTITUTES ACCEPTANCE OF THESE TERMS OF USE (“TERMS”), AS SUCH MAY BE REVISED BY B.HIVE FROM TIME TO TIME, AND IS A BINDING AGREEMENT BETWEEN THE USER (“USER”), AND The B.HIVE CAFÉ CORPORATION , GOVERNING THE USE OF THE APPLICATION. IF USER DOES NOT AGREE TO THESE TERMS, USER SHOULD UNINSTALL THIS APPLICATION IMMEDIATELY. THESE TERMS CONTAIN DISCLAIMERS AND OTHER PROVISIONS THAT LIMIT OUR LIABILITY TO USER.

These terms include an Arbitration provision that governs any disputes between you and us. Except where prohibited by law, this provision will:

Eliminate your right to a trial by jury; and
Substantially affect your rights, including preventing you from bringing, joining or participating in class or consolidated proceedings.
You agree that we may provide notices, disclosures and amendments to these Terms by electronic means, including by changing these Terms within the Application or by posting revisions on the B.Hive Website.


Eligibility
The Application is not targeted towards, nor intended for use by, anyone under the age of 13. A USER MUST BE AT LEAST AGE 13 TO ACCESS AND USE THE APPLICATION. If the User is between the ages of 13 and the age of majority in his or her province/territory of residence, he or she may only use the Application under the supervision of a parent or legal guardian who agrees to be bound by these Terms.
In order to use certain functions of our Application, you will need to register for an account. You agree to (a) create only one account; (b) provide accurate, truthful , current and complete information when creating your account; (c) maintain and promptly update your account information; (d) maintain the security of your account by not sharing your password with others and restricting access to your account and your computer; (e) promptly notify B.HIVE if you discover or otherwise suspect any security breaches relating to the Application; and (f) take responsibility for all activities that occur under your account and accept all risks of unauthorized access.

Privacy
Please read the Privacy Policy carefully to understand how B.HIVE collects, uses and discloses personally identifiable information from its users. By downloading, installing, accessing or using the Application, you consent to all actions that we take with respect to your data consistent with our Privacy Policy. 

Third Party Terms and Conditions; B.HIVE Policies
These Terms supplement and incorporate (i) the terms and conditions of any site from which User downloads the Application (including Google Play, the Amazon Appstore, and the Android Market) (“Third Party Terms”) and (ii) other B.HIVE policies. If any of the provisions of the Third Party Terms or any applicable B.HIVE policies conflict with these Terms, these Terms will control, solely to the extent such terms apply to the Application.


Mobile Payment
Users who download the Application to a Device may also elect to participate in certain functionality of the Application which will allow the User to use a Device to purchase B.HIVE products (a) using a digital B.HIVE Card and/or (b) by linking a credit card, debit card or mobile wallet to your account, and using it to pay directly for the products through the Application (“Mobile Payment”). Mobile Payment is accepted at all company operated B.HIVE retail locations and some B.HIVE licensed stores. B.HIVE reserves the right at any time to discontinue Mobile Payment or change the location of stores accepting Mobile Payment.

Mobile Order and Pay (MOP)
Users who download the Application to a Device may also elect to participate in certain functionality of the Application which will allow the User in certain B.HIVE retail locations in certain markets to use the Application to order and pay for certain B.HIVE products prior to arrival at the store (“MOP”). B.HIVE reserves the right to limit the ordering options available through MOP, including a limit of twelve (12) or fewer of each potential beverage modifier (e.g., number of espresso shots, number of pumps of flavored syrup, etc.) per each MOP item ordered. B.HIVE reserves the right at any time to discontinue MOP, to change the location of stores or markets offering MOP, and/or to change the ordering options and limitations for items through MOP.

Email Communications, Push Notifications, and In-App Messages
If a User signs up for a B.HIVE account using the Application, the User may choose to opt in to receive promotional email communications from B.HIVE (“Email Communications”). The User may, at any time, opt out of receiving Email Communications from B.HIVE by adjusting the User’s profile settings.
Similarly, upon download of this Application, the User is provided the option to opt in to receive push notifications from B.HIVE on his or her Device. This may include promotional communications, offers, and system messages pushed to the Device or within the Application mailbox (“Push Notifications”). The User may, at any time following download of this Application, opt out of receiving Push Notifications by type by adjusting the “B.HIVE Notifications” switch within the Application settings to “off”, or within the Device’s settings application under “Notifications” to completely opt out of Push Notifications. Opting out of Push Notifications will not affect User settings with respect to Email Communications.
Finally, by using this Application, in-app messages will automatically be displayed to the User via the Application’s display tiles and/or sent to the User via the Application’s inbox, including promotional communications and offers. If the User does not wish to see or receive such messages, the User must cease use of the Application.

Copyright, Trademarks, and User License
Unless otherwise indicated, the Application and all content and other materials therein, including, without limitation, the B.HIVE logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Application Materials”) are the property of B.HIVE or its licensors or users and are protected by Canadian and international copyright laws. B.HIVE Coffee Company, B.HIVE, the B.HIVE logo, and other B.HIVE trademarks, service marks, graphics, and logos used in connection with the Application are trade names, trademarks or registered trademarks of B.HIVE Corporation (collectively “B.HIVE Marks”). Other trademarks, service marks, graphics and logos used in connection with the Application are the trademarks or registered trademarks of their respective owners (collectively “Third Party Marks”). The B.HIVE Marks and Third-Party Marks may not be copied, imitated, or used, in whole or in part, without the prior written permission of B.HIVE or the applicable trademark holder. The Application and the Content are protected by copyright, trademark, patent, trade secret, international treaties, provincial and federal laws, and other proprietary rights and also may have security components that protect digital information only as authorized by B.HIVE or the owner of the Content. All rights not expressly granted are reserved. 

Subject to these Terms, B.HIVE grants the User a personal, non-exclusive, non-transferable, limited, and revocable license to use the Application for personal use only in accordance with these Terms (“User License”). Any use of the Application in any other manner, including, without limitation, resale, transfer, modification or distribution of the Application or text, pictures, music, barcodes, video, data, hyperlinks, displays, and other content associated with the Application (“Content”) is prohibited. Unless explicitly stated herein, nothing in these Terms shall be construed as conferring in any manner, whether by implication, estoppel or otherwise, any title or ownership of, or exclusive use-rights to, any intellectual property or other right and any goodwill associated therewith These Terms and User License also govern any updates to, or supplements or replacements for, the Application, unless separate terms accompany such updates, supplements, or replacements, in which case the separate terms will apply.

Acceptable Use
User’s use of the Application, any Content, and any information provided by the User including user names and passwords, addresses, e-mail addresses, phone number, financial information (such as credit card numbers), information related to a B.HIVE Card, employer name, or GPS location (“User Information”) transmitted in connection with the Application is limited to the contemplated functionality of the Application. In no event may the Application be used in a manner that (a) harasses, abuses, stalks, threatens, defames, or otherwise infringes or violates the rights of any other party (including but not limited to rights of publicity or other proprietary rights); (b) is unlawful, fraudulent, or deceptive; (c) provides sensitive personal information unless specifically requested by B.HIVE, (d) includes spam or any unsolicited advertising; (e) uses technology or other means to access B.HIVE or Content that is not authorized by B.HIVE; (f) uses or launches any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” to access B.HIVE or Content; (g) attempts to introduce viruses or any other computer code, files, or programs that interrupt, destroy, or limit the functionality of any computer software, hardware, or telecommunications equipment; (h) attempts to gain unauthorized access to B.HIVE’ computer network or user accounts; (i) encourages conduct that would constitute a criminal offense or that gives rise to civil liability; (j) violates these Terms; (k) attempts to damage, disable, overburden, or impair B.HIVE’ servers or networks; (l) impersonates any person or entity or otherwise misrepresents your identity or affiliation with another person or entity; or (m) fails to comply with applicable third party terms (collectively “Acceptable Use”). B.HIVE reserves the right, in its sole discretion, to terminate any User License, terminate any User’s participation in Mobile Payment or MOP, remove Content, or assert legal action with respect to Content or use of the Application, including Mobile Payment or MOP, that B.HIVE reasonably believes is or might be in violation of these Terms, Third Party Terms, or B.HIVE policies including the B.HIVE Card Terms and Conditions. B.HIVE’ failure or delay in taking such actions does not constitute a waiver of its rights to enforce these Terms. B.HIVE requests that Users not use the Application, including that they not place orders through MOP, while driving.

Indemnification
The User agrees to defend, indemnify, and hold harmless B.HIVE, its parent, subsidiary and other affiliated companies, independent contractors, service providers and consultants, and their respective employees, contractors, agents, officers, and directors (“B.HIVE Indemnitees”) from any and all claims, suits, damages, costs, lawsuits, fines, penalties, liabilities, and expenses (including attorneys’ fees) (“Claims”) that arise from or relate to the User’s use or misuse of the Application (including Mobile Payment or MOP), violation of these Terms, or violation of any rights of a third party. Notwithstanding the foregoing, this indemnification provision shall not apply to any Claims caused by a B.HIVE Indemnitee’s sole negligence. B.HIVE reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by the User, in which event the User will cooperate in asserting any available defenses.

Warranties; Disclaimers
B.HIVE IS PROVIDING THE APPLICATION TO THE USER “AS IS” AND THE USER IS USING THE APPLICATION AT HIS OR HER OWN RISK. TO THE FULLEST EXTENT ALLOWABLE UNDER APPLICABLE LAW, B.HIVE DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES THAT THE APPLICATION IS MERCHANTABLE, RELIABLE, AVAILABLE, ACCURATE, FIT FOR A PARTICULAR PURPOSE OR NEED, NON-INFRINGING, FREE OF DEFECTS OR VIRUSES, ABLE TO OPERATE ON AN UNINTERRUPTED BASIS, THAT THE USE OF THE APPLICATION BY THE USER IS IN COMPLIANCE WITH LAWS APPLICABLE TO THE USER, THAT USER INFORMATION OR ORDERS TRANSMITTED IN CONNECTION WITH THE APPLICATION (INCLUDING AS PART OF MOBILE PAYMENT OR MOP) WILL BE SUCCESSFULLY, ACCURATELY, OR SECURELY TRANSMITTED OR RECEIVED, THAT ORDERS WILL BE AS PLACED OR READY AT THE SUGGESTED TIME, OR THAT ANY PARTICULAR ITEM ORDERED WILL BE AVAILABLE. THE MATERIALS AND INFORMATION IN THE APPLICATION MAY INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS.
ANY PRODUCTS AND/OR SERVICES DESCRIBED ON THE APPLICATION ARE OFFERED IN JURISDICTIONS WHERE THEY MAY BE LEGALLY OFFERED FOR SALE. THE INFORMATION AVAILABLE ON OR THROUGH THE APPLICATION IS NOT AN OFFER OR SOLICITATION BY ANYONE TO ANYONE IN ANY JURISDICTION IN WHICH AN OFFER OR SOLICITATION CANNOT LEGALLY BE MADE, OR TO ANY PERSON TO WHOM IT IS UNLAWFUL TO MAKE A SOLICITATION.

No Liability
SUBJECT TO APPLICABLE LAW, IN NO EVENT SHALL B.HIVE OR ITS OFFICERS, DIRECTORS, EMPLOYEES, SHAREHOLDERS OR AGENTS (A) BE LIABLE TO THE USER WITH RESPECT TO USE OF THE APPLICATION, INCLUDING WITHOUT LIMITATION PARTICIPATION IN MOBILE PAYMENT OR MOP, THE CONTENT OR THE MATERIALS CONTAINED IN OR ACCESSED THROUGH THE APPLICATION, OR ANY DAMAGES THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO B.HIVE' RECORDS, PROGRAMS OR SERVICES; AND (B) BE LIABLE TO THE USER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, LOST PROFITS, LOSS, THEFT OR CORRUPTION OF USER INFORMATION, THE INABILITY TO USE THE APPLICATION OR ANY OF ITS FEATURES OR DEVICE FAILURE OR MALFUNCTION. THE USER’S SOLE REMEDY IS TO CEASE USE OF THE APPLICATION OR TO CEASE PARTICIPATION IN MOBILE PAYMENT OR MOP.
YOUR JURISDICTION MAY NOT ALLOW THE LIMITATION OF LIABILITY IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THESE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.

Third Party Content, Applications, Products and Services (including Advertising and Promotions)
B.HIVE may provide third party content in the Application (including embedded content) or links to third party content, applications, products and services, including advertisements and promotions (collectively, “Third Party Content”) as a service to those interested in this information. We do not control, endorse or adopt any Third-Party Content, including that the inclusion of any link does not imply affiliation, endorsement or adoption by B.HIVE of any application or any information contained therein, and can make no guarantee as to its accuracy or completeness. You acknowledge and agree that B.HIVE is not responsible or liable in any manner for any Third-Party Content and undertakes no responsibility to update or review such Third-Party Content. You agree to use such Third-Party Content contained therein at your own risk. When you use other applications via Third-Party Content, or participate in promotions or business dealings with third parties, you should understand that our terms and policies no longer govern, and that the terms and policies of those third-party applications will now apply. You should review the applicable terms and policies, including privacy and data gathering practices, of any application to which you navigate from our Application. You must comply with any applicable third-party terms when using the Application.

Modifications to the Application
B.HIVE reserves the right to modify or discontinue, temporarily or permanently, the Application or any features or portions thereof without prior notice. You agree that B.HIVE will not be liable for any modification, suspension or discontinuance of the Application or any part thereof.

Arbitration
Please read this section carefully. It affects rights that you may otherwise have. It provides for resolution of most disputes through arbitration instead of court trials and class actions. Arbitration is more informal than a lawsuit in court, uses a neutral arbitrator instead of a judge or jury, and discovery is more limited. Arbitration is final and binding and subject to only very limited review by a court. This arbitration clause shall survive termination of these Terms.

Binding Arbitration.　This provision is intended to be interpreted broadly to encompass all disputes or claims arising out of or relating to these Terms, your use of the Application, and your relationship with us. Any dispute or claim arising out of or relating to these Terms or use of the Application and your relationship with B.HIVE or any subsidiary, parent or affiliate company or companies (whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory) will be resolved by binding arbitration, except that either of us may take claims to small claims court if they qualify for hearing by such a court.

Arbitration Procedures.　For all disputes, whether pursued in court or arbitration, you must first send a written description of your claim to our Customer Service department to allow us an opportunity to resolve the dispute. You and we each agree to negotiate your claim in good faith. You may request arbitration if your claim or dispute cannot be resolved within 60 days.
The arbitration of any dispute or claim shall be conducted and finally resolved in accordance with the rules of the Canadian Arbitration Association ("CAA"), including the CAA's Arbitration Rules (as applicable), as modified by these Terms. The CAA Rules and information about arbitration and fees are available online at https://canadianarbitrationassociation.ca. Any arbitration will be held in a reasonably convenient location in the province in which you reside or at another mutually agreed location. The arbitration will be conducted in the English language unless otherwise mutually agreed by us in writing or otherwise required by law. An arbitrator may award on an individual basis any relief that would be available in a court, including injunctive or declaratory relief to the extent required to satisfy your individual claim, and must follow and enforce these Terms as a court would. Any arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award. Judgment on any arbitration award may be entered in any court having proper jurisdiction. There will be no appeal from the decision of the arbitrator on questions of fact, law, or mixed fact and law.

Costs of Arbitration.　 Each party will bear the fees and expense of its own attorneys, experts, witnesses and preparation and presentation of evidence at the arbitration. 

Class Action Waiver and Jury Waiver.　Unless otherwise prohibited by law, you and we each agree that any proceeding, whether in arbitration or in court, will be conducted only on an individual basis and not in a class, consolidated or representative action. If a court or arbitrator determines in an action between you and us that this class action waiver is unenforceable, the arbitration agreement will be void as to you. If for any reason a claim proceeds in court rather than through arbitration, you and we each waive any right to a jury trial.

Governing Law and Jurisdiction
These Terms and use of the Application are governed by the laws of Canada and the law of the Province of Quebec applicable therein, without resort to conflict of law provisions. The United Nations Convention on Contracts for the International Sale of Goods shall have no applicability. If the arbitration agreement is ever deemed unenforceable or void or a dispute between the parties is not subject to arbitration, the User irrevocably consents to the exclusive jurisdiction of the courts in Montreal, Quebec, Canada for purposes of any legal action arising out of or related to the use of the Application or these Terms.

Termination
Notwithstanding any of these Terms, B.HIVE reserves the right, without notice and in its sole discretion, to terminate your license to use the Application and to block or prevent your future access to and use of the Application. B.HIVE’ failure or delay in taking such actions does not constitute a waiver of its rights to enforce these Terms.

Changes
B.HIVE reserves the right to change or modify these Terms or any other B.HIVE policies related to use of the Application at any time and at its sole discretion by changing these Terms within the Application or by posting revisions on the B.HIVE Website. Continued use of the Application following such changes or modifications to the Terms or other B.HIVE policies will constitute acceptance of such changes or modifications. If you do not agree to such changes or modifications, you should uninstall the Application immediately.

Severability
If any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.

Language
By using the English version of the Application, the parties acknowledge and agree that they have required that this Agreement be prepared in the English language. En utilisant la version anglaise de l’application, les parties reconnaissent avoir exigé que la présente convention soit rédigée en anglais.

Contact
Any questions, complaints, or claims regarding the Application should be directed to:

THE B.HIVE CAFÉ CORPORATION
contact@thebhive.io
2313 Saint Catherine, 106/107
Montreal, QC H3H 1N2
` 
});
  result.push({ privacy: `Please read the following provisions carefully to understand how B.HIVE collects, uses and discloses personally identifiable information from its users, including with respect to the B.HIVE mobile application (“Application”). By downloading, installing, accessing or using the Application, you consent to all actions that we take with respect to your data consistent with our Privacy Policy and the following provisions.

User Information
Some functionality of the Application, including using a device operating on an Android platform (“Device”) to purchase B.HIVE products in the same manner as is possible with a B.HIVE stored value card (“B.HIVE Card”) (“Mobile Payment”), using the Application to order and pay for certain B.HIVE products using a B.HIVE stored value card prior to arrival at the store (“MOP”), location-based services and functionality, iBeacons or other location-based technology to enhance the user experience, and access of User’s address book may require the transmission of information provided by the User including user names and passwords, addresses, e-mail addresses, phone number, financial information (such as credit card numbers), information related to a B.HIVE Card, employer name, or GPS location (“User Information”). In order to use certain Application functionality, such as MOP and location-based services and technology, User must either (a) enable “location services” in the Application; and/or (b) set the permissions in his or her mobile device to allow communication of this information. If the User uses such Application functionality, the User consents to the transmission of User Information to B.HIVE and/or its agents, and authorizes B.HIVE and/or its agents to record, process, and store such User Information as necessary for the Application functionality and for purposes described in the B.HIVE Privacy Policy. Please see the Privacy Policy for more information about how we may use and store such User Information, and how to opt out of sharing User Information, including GPS location.
  
  
The User is solely responsible for maintenance of the confidentiality and security of any User Information which the User transmitted from or stored on a Device for purposes of the Application, including Mobile Payment and MOP, for all transactions and other activities undertaken with any B.HIVE Card registered in the User’s name, whether authorized or unauthorized. The User agrees to immediately notify B.HIVE of any unauthorized transactions associated with the Application including Mobile Payment and MOP, or any other breach of security. B.HIVE shall not be responsible for any losses arising out of the loss or theft of User Information which the User transmitted from or stored on a Device or from unauthorized or fraudulent transactions associated with the Application.
  
Email Communications and Push Notifications
If a User signs up for a B.HIVE account using the Application, the User will have the opportunity to opt-in to receive promotional email communications from B.HIVE (“Email Communications”). Thereafter, the User may opt out of receiving Email Communications solely by adjusting the User’s profile settings.
  
Similarly, upon download of this Application, the User is, provided the option to opt into receive push notifications from B.HIVE on their Device and within the Application. This may include promotional communications, Pick of the Week offers, and system messages pushed to the Device or within the Application mailbox (“Push Notifications”). The User may, at any time following download of this Application, opt out of receiving Push Notifications by type by adjusting the “B.HIVE Notifications” switch within the Application settings to “off", or within the Device’s settings application under "Notifications" to completely opt out of Push Notifications. Opting out of Push Notifications will not affect User settings with respect to Email Communications.
  ` });
  res.status(201).send(result);
});

module.exports = router;
